version: '3.8'

services:
  client:
    build:
      context: /frontend
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: /backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://collabs:27017
      - JWT_SECRET=secret
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    command: >
      mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
